# Generated by Django 5.1.3 on 2024-11-14 22:54

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        VectorExtension()
    ]
