# Generated by Django 5.1.3 on 2024-11-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pgvec_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incident',
            options={'managed': False},
        ),
    ]
