# HOST = "localhost"
HOST = "db"
# DBNAME = "TMU Security Data"
DBNAME = "tmusecurity"
#USER = "postgres"
USER = "postgres"
# PASSWORD = "ghau8msj860"
PASSWORD = "postgres"
PORT = 5432
TABLE_NAME = "incidents"
DB_PARAMS = {'host':HOST, 'dbname':DBNAME, 'user':USER, 'password':PASSWORD}