name: Sync Prod Branch

on:
  push:
    branches:
      - main

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Sync prod
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        
        # Checkout the prod branch
        git checkout prod
        
        # Merge main into the branch
        git merge main
        
        # Remove Dockerfiles, docker-compose files, and .env files
        find . -name "Dockerfile*" -delete
        find . -name "docker-compose*" -delete
        find . -name ".env*" -delete
        
        # Stage and commit changes
        git add .
        git commit -m "Sync with main branch, removing Docker-related files" || echo "No changes to commit"
        
        # Push changes
        git push origin prod